/**
 * # SVG Helper
 *
 * Provide general helper functionality for working with SVG files.
 *
 * @module nag.svg
 * @ngservice svgHelper
 */
angular.module('nag.svg')
.factory('nagSvgHelper', [
  '$timeout',
  function($timeout) {
    var svgHelper = {
      /**
       * Passes in a DOM element to use to inject SVG.
       *
       * @todo: add example
       *
       * @method getAsyncTemplate
       *
       * @param {DOMElement|[DOMElement]} elements Remote path to the template file
       */
      inject: function(elements) {
        if(window.IconicJS) {
          //since it is possible for the src to be generated by an angular value, this needs to be processed on the next javascript loop
          $timeout(function() {
            window.IconicJS().inject(elements);
          }, 0);
        } else if(window.SVGInjector ) {
          //since it is possible for the src to be generated by an angular value, this needs to be processed on the next javascript loop
          $timeout(function() {
            window.SVGInjector(elements);
          }, 0);
        }
      }
    }

    return svgHelper;
  }
]);
